language: objective-c
osx_image: xcode61
rvm: 2.1.0
notifications:
  email: false
podfile: project/Podfile
script:
  - xctool test -workspace project/project.xcworkspace -scheme project -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool build -workspace example/SugarRecordExample.xcworkspace -scheme SugarRecordExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO