language: objective-c
osx_image: xcode7.1
notifications:
  email: false
install:
- brew install carthage
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- carthage bootstrap --no-use-binaries
script:
- make build
- make test
