language: objective-c
xcode_sdk: iphonesimulator
rvm: 1.9.3
before_install:
  - cd SugarRecordDemo
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
  - gem install xcpretty
script:
  - xcodebuild -workspace SugarRecord.xcworkspace -scheme SugarRecordTests ONLY_ACTIVE_ARCH=YES test | xcpretty -tc --no-utf;
