language: objective-c
osx_image: xcode7.1
notifications:
  email: false
install:
- brew install carthage
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- carthage update
script:
- set -o pipefail && xcodebuild test -project SugarRecord/SugarRecord.xcodeproj -scheme "SugarRecord-iOS" ONLY_ACTIVE_ARCH=NO | xcpretty -c
- set -o pipefail && xcodebuild build -project SugarRecord/SugarRecord.xcodeproj -scheme "SugarRecord-iOS" ONLY_ACTIVE_ARCH=NO | xcpretty -c
