language: objective-c
xcode_sdk: iphonesimulator
rvm: 1.9.3

before_install:
  - cd SugarRecordDemo
  - gem install --no-rdoc --no-ri cocoapods -v 0.34.1

script:
- xcodebuild -workspace SugarRecord.xcworkspace -scheme SugarRecordTests test
